name: .NET

on:
  push:
    branches: [ "main", "ci-sonarcloud" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: calculator-webapp    
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  DOTNET_VERSION: '2.1.x' 

jobs:
  build:
    name: Build, Analyze and Publish Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET

      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      #Run Sonar tasks
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    
    #Publish Artifact
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/drop
      
    - name: Upload a Build Artifact for deployment job
      uses: actions/upload-artifact@v3.1.2
      with:
        name: .net-app       
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/drop
  
      
  Deploy:
    name: Deploy to Azure - Webapp service
    runs-on: ubuntu-latest    
    needs: build
    environment: 
      name: 'Dev'

    steps:      
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: .net-app 

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Publish on Azure WebApp
        uses: Azure/webapps-deploy@v2.2.5
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: 'dev'
          package: .net-app
          
          
          
          
          
